steps:
#First Clone from Google Cloud Source Repository  
- name: 'gcr.io/cloud-builders/git'
  args: ['clone','https://source.developers.google.com/p/${_PROJECT}/r/${_REPO_NAME}']
  id: 'push-gcloud-source-repository'
steps:
- name: "gcr.io/cloud-builders/mvn"
  args: ["clean", "package","appengine:deploy"]
  id: 'deploying-to-appengine'
  waitFor: ['push-gcloud-source-repository']
  
